name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nebulex_test:
    name: 'NebulexCachexAdapter Test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - elixir: 1.11.x
            otp: 23.x
            coverage: true
          - elixir: 1.10.x
            otp: 23.x
          - elixir: 1.10.x
            otp: 22.x
          - elixir: 1.9.x
            otp: 22.x

    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      MIX_ENV: test
      NEBULEX_PATH: nebulex

    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '${{ matrix.otp }}'
          elixir-version: '${{ matrix.elixir }}'

      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: deps
          key: >-
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-

      - name: Cache _build
        uses: actions/cache@v1
        with:
          path: _build
          key: >-
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          git clone --depth 1 --branch master https://github.com/cabol/nebulex.git

      - name: Run style and code consistency checks
        run: |
          mix compile --warnings-as-errors
          mix format --check-formatted
          mix credo --strict

      - name: Run tests
        run: |
          epmd -daemon
          mix test --trace
        if: ${{!matrix.coverage}}

      - name: Run tests with coverage
        run: |
          epmd -daemon
          mix coveralls.github
        if: ${{matrix.coverage}}

      - name: Cache PLT
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: '${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt-v1'
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt-v1

      - name: Run static analysis checks
        run: |
          mix sobelow --exit --skip
          mix dialyzer --format short
